### ISSUE TITLE
Matrix inside of Super Table doesn't seem to work

### ISSUE THREAD

**Issue by joshuapease** [doublesecretagency/craft-spoon#108]
## Description

Thanks so much for your help! I'm working on a project that uses a Super Table field that contains a nested Matrix field. We're hoping to create groups for the Matrix blocks. 

The plugin UI shows the nested Matrix field, and even lets me create our desired block groups. 

<img width="400" src="https://user-images.githubusercontent.com/2145998/113950815-1e71e980-97c7-11eb-82ee-35075609cbf7.png">

<img width="400" src="https://user-images.githubusercontent.com/2145998/113950837-2a5dab80-97c7-11eb-89b8-81afafc36cff.png">

However, once I go to use the field in an entry, there are no groups or  UI change for the nested Matrix field. 

<img width="600" src="https://user-images.githubusercontent.com/2145998/113950942-655fdf00-97c7-11eb-829d-9baf515505f6.png">

Here's a Matrix field that isn't nested with the same groups. 

<img src="https://user-images.githubusercontent.com/2145998/113951015-87596180-97c7-11eb-9c15-499f67c19dda.png" width="600">

## Sample Repo
I've created a sample repo with the plugins installed and the fields, spoon groups, and entry types set up. I set this site up with Nitro 2 running PHP 7.4

https://github.com/joshuapease/craftcms-spoon-test

## Steps to reproduce
1. Install the latest Super Table and Spoon plugins on the latest version Craft CMS. 
2. Create a Super Table field that contains a Matrix field with at least two blocks. 
3. Use Spoon to set up groups for the nested Matrix field. 
4. Add the field to an entry type and try to create blocks. 

--- 

### CMS & Plugin Versions
```
"craftcms/cms": "^3.6.4",
"angellco/spoon": "^3.6",
"verbb/super-table": "2.6.7",
"vlucas/phpdotenv": "^3.4.0"
```

### Server Info
![image](https://user-images.githubusercontent.com/2145998/113951363-4b72cc00-97c8-11eb-9094-a70a9907d3f2.png)

**Comment by paulwaddington** [comment]
We're seeing the exact same issue and use this plugin across all of sites!

**Comment by mudechs** [comment]
Same here

**Comment by marc524** [comment]
Is there an ETA on this being fixed? Still seeing this in Spoon 3.6.1

**Comment by joshangell** [comment]
Hey everyone - sorry for the radio silence, not going to lie I’ve been absolutely slammed just trying to stay afloat. I am hopeful I’ll have some free time soon to tackle some of the issues on this plugin, including this one. If I can it’ll be in the next 6 weeks or so.

**Comment by kgollert** [comment]
Same here. Sadly the plugin stays `disabled` and is waiting for the fix since a year now :(

**Comment by lindseydiloreto** [comment]
Hello everyone! I'm happy to say that Super Table compatibility has been restored in the latest version of Spoon. 🙏 

To be clear, **Spoon 4.0** is now compatible with Super Table on **Craft 4.x**. (We won't be backporting this to Craft 3.x, but the fix will be waiting for you when you do eventually update to C4!)
