### ISSUE TITLE
Question: more detailed config (spoon.php) example

### ISSUE THREAD

**Issue by terryupton** [doublesecretagency/craft-spoon#113]
Hey Josh.

Do you have a more detailed example of how to use the config file to setup Spoon?
I would like to use a config file so I can re-use it across projects for some matrix fields.

I am unsure how t structure this on the config file and what to define etc.

Thanks
Terry

**Comment by lindseydiloreto** [comment]
Hi Terry,

I've just published some new docs, which includes a page about the PHP config file...

https://plugins.doublesecretagency.com/spoon/getting-started/config/

Not much to it, there's only a single setting available (`nestedSettings`).

I know it's a little late, but I hope that helps! 🙂
