### ISSUE TITLE
Matrix field groups are not working inside supertable

### ISSUE THREAD

**Issue by iicuken** [doublesecretagency/craft-spoon#115]
I have all latest staff: craftcms, supertable plugin, spoon plugin, installed via composer.
My php version is 7.4. My webserver is lighttpd.
I have 2 fresh craft installs, 1 is for web site, and second  - super fresh is for craft testing.
And on both i have same issue:
 Field groups are working on simple matrix field perfectly.
 But on matrix field inside Supertable they not working at all.
Pls help.

**Comment by lindseydiloreto** [comment]
This is now fixed in **Spoon 4.0** (compatible with Craft 4).

Thanks for reporting! 👍
